### ISSUE TITLE
docs: add instructions for chaincode upgrade

### ISSUE THREAD

**Issue by AurelienGasser** [Substra/hlf-k8s#50]
There are currently no instructions on how to upgrade the chaincode version on a running installation.

**Comment by Kelvin-M** [comment]
You can find more information here : https://hyperledger-fabric.readthedocs.io/en/release-1.4/chaincode4noah.html#upgrade
and https://hyperledger-fabric.readthedocs.io/en/release-1.4/commands/peerchaincode.html#peer-chaincode-upgrade-example

We have also a chaincode upgrade instructions in the docker-compose version : 
https://github.com/SubstraFoundation/hlf-k8s/blob/master/python-scripts/utils/run_utils.py#L254
It is based on the fabric-sdk-py client : https://github.com/hyperledger/fabric-sdk-py/blob/master/hfc/fabric/client.py#L1395

Be careful, depending on the policy, the transaction must be endorsed by multiple peers, so you should use :
```
--peerAddresses stringArray
--tlsRootCertFiles stringArray
```
https://hyperledger-fabric.readthedocs.io/en/release-1.4/commands/peerchaincode.html#peer-chaincode-upgrade
